import * as request from "supertest";
import {expect} from "chai";

import * as app from "../../../app";
import {sortedStringify} from "../../constants";

const expectedResult = {
    "0":   "aberdeen city",
    "1":   "aberdeenshire",
    "2":   "angus",
    "3":   "antrim",
    "4":   "argyll and bute",
    "5":   "armagh",
    "6":   "bath and ne somerset",
    "7":   "bedfordshire",
    "8":   "blackburn with darwen",
    "9":   "blackpool",
    "10":  "blaenau gwent",
    "11":  "bournemouth",
    "12":  "bracknell forest",
    "13":  "bridgend",
    "14":  "brighton and hove",
    "15":  "bristol, city of",
    "16":  "buckinghamshire",
    "17":  "caerphilly",
    "18":  "cambridgeshire",
    "19":  "cardiff",
    "20":  "carlow",
    "21":  "carmarthenshire",
    "22":  "cavan",
    "23":  "ceredigion",
    "24":  "cheshire",
    "25":  "city of edinburgh",
    "26":  "clackmannanshire",
    "27":  "clare",
    "28":  "conwy",
    "29":  "cork",
    "30":  "cornwall and isles of scilly",
    "31":  "cumbria",
    "32":  "darlington",
    "33":  "denbighshire",
    "34":  "derby",
    "35":  "derbyshire",
    "36":  "devon",
    "37":  "donegal",
    "38":  "dorset",
    "39":  "down",
    "40":  "dublin",
    "41":  "dumfries and galloway",
    "42":  "dundee city",
    "43":  "durham",
    "44":  "east ayrshire",
    "45":  "east dunbartonshire",
    "46":  "east lothian",
    "47":  "east renfrewshire",
    "48":  "east riding of yorkshire",
    "49":  "east sussex",
    "50":  "essex",
    "51":  "falkirk",
    "52":  "fermanagh",
    "53":  "fife",
    "54":  "flintshire",
    "55":  "galway",
    "56":  "glasgow city",
    "57":  "gloucestershire",
    "58":  "greater london",
    "59":  "greater manchester",
    "60":  "gwynedd",
    "61":  "halton",
    "62":  "hampshire",
    "63":  "hartlepool",
    "64":  "herefordshire",
    "65":  "hertfordshire",
    "66":  "highland",
    "67":  "inverclyde",
    "68":  "isle of anglesey",
    "69":  "isle of man",
    "70":  "isle of wight",
    "71":  "kent",
    "72":  "kerry",
    "73":  "kildare",
    "74":  "kilkenny",
    "75":  "kingston upon hull, city of",
    "76":  "lancashire",
    "77":  "laois",
    "78":  "leicester",
    "79":  "leicestershire",
    "80":  "leitrim",
    "81":  "limerick",
    "82":  "lincolnshire",
    "83":  "londonderry",
    "84":  "longford",
    "85":  "louth",
    "86":  "luton",
    "87":  "mayo",
    "88":  "meath",
    "89":  "medway",
    "90":  "merseyside",
    "91":  "merthyr tydfil",
    "92":  "middlesbrough",
    "93":  "midlothian",
    "94":  "milton keynes",
    "95":  "monaghan",
    "96":  "monmouthshire",
    "97":  "moray",
    "98":  "na h-eileanan siar",
    "99":  "neath port talbot",
    "100": "newport",
    "101": "norfolk",
    "102": "north ayrshire",
    "103": "north east lincolnshire",
    "104": "north lanarkshire",
    "105": "north lincolnshire",
    "106": "north somerset",
    "107": "north yorkshire",
    "108": "northamptonshire",
    "109": "northumberland",
    "110": "nottingham",
    "111": "nottinghamshire",
    "112": "offaly",
    "113": "orkney islands",
    "114": "oxfordshire",
    "115": "pembrokeshire",
    "116": "perth and kinross",
    "117": "peterborough",
    "118": "plymouth",
    "119": "poole",
    "120": "portsmouth",
    "121": "powys",
    "122": "reading",
    "123": "redcar and cleveland",
    "124": "renfrewshire",
    "125": "rhondda, cynon, taff",
    "126": "roscommon",
    "127": "rutland",
    "128": "scottish borders",
    "129": "shetland islands",
    "130": "shropshire",
    "131": "sligo",
    "132": "slough",
    "133": "somerset",
    "134": "south ayrshire",
    "135": "south gloucestershire",
    "136": "south lanarkshire",
    "137": "south yorkshire",
    "138": "southampton",
    "139": "southend-on-sea",
    "140": "staffordshire",
    "141": "stirling",
    "142": "stockton-on-tees",
    "143": "stoke-on-trent",
    "144": "suffolk",
    "145": "surrey",
    "146": "swansea",
    "147": "swindon",
    "148": "telford and wrekin",
    "149": "the vale of glamorgan",
    "150": "thurrock",
    "151": "tipperary",
    "152": "torbay",
    "153": "torfaen",
    "154": "tyne and wear",
    "155": "tyrone",
    "156": "warrington",
    "157": "warwickshire",
    "158": "waterford",
    "159": "west berkshire",
    "160": "west dunbartonshire",
    "161": "west lothian",
    "162": "west midlands",
    "163": "west sussex",
    "164": "west yorkshire",
    "165": "westmeath",
    "166": "wexford",
    "167": "wicklow",
    "168": "wiltshire",
    "169": "windsor and maidenhead",
    "170": "wokingham",
    "171": "worcestershire",
    "172": "wrexham",
    "173": "york"
};

describe("GET /v1/map/:map/regionType/:regionType/regions", () => {
    it("responds with json", async () => {
        const response = await request(app)
            .get("/v1/map/uk-flood-test/region-type/county/regions")
            .set("Accept", "application/json");
        console.log(sortedStringify(response.body));
        expect(sortedStringify(response.body)).to.equal(sortedStringify(expectedResult));
    });
});
