// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region":           "eu-west-2",
  "aws_cognito_identity_pool_id": "eu-west-2:c8ea0906-162a-40f4-973b-eaac52c7d371",
  "aws_cognito_region":           "eu-west-2",
  "aws_user_pools_id":            "eu-west-2_qvOKMX2BJ",
  "aws_user_pools_web_client_id": "2up86t9t8eq21nkq472im2eohu",
  "oauth":                        {}
};


export default awsmobile;
